/* Generated by update-image-index.ps1. Do not edit manually. */
window.IMAGE_FILES = [
  "images/_cel_shading_anime_style_long_black_hair_mature_and_graceful__f9447b77-b822-45a0-bc8f-a431b0b8cc77_3.png",
  "images/_cel_shading_anime_style_warm_color_tones_magical_and_dreamy__7e65091c-73f0-410f-ab6d-7f55ff882e85_0.png",
  "images/_impasto_painting_style_semi-realistic_style_exquisite_fantas_78cc9927-7dc7-4928-92fe-bf55a79ae9fa_0.png",
  "images/_impasto_painting_style_semi-realistic_style_exquisite_fantas_78cc9927-7dc7-4928-92fe-bf55a79ae9fa_1.png"
];