// Niji 提示詞詞庫
// 依 niji 7 的寫作順序排列：先「畫面設定」（風格→構圖→氛圍→光影→場景），
// 再「角色設定」（性別→髮型→眼睛→表情→服裝→動作）。
// 提示詞輸出會依此順序自動排序，與點選順序無關。
// 每個分類：group = 所屬大類、hue = 代表色相(0-360，用於選中詞的顏色區分)
// 每個詞：zh = 顯示名稱、en = 實際提示詞、slug = 詞彙唯一鍵（wordIndex 的索引鍵）
// gender = "f"（女性專屬）/ "m"（男性專屬），未標示 = 通用（兩種性別都顯示）。
// 分類本身也可標 gender（如「臉部毛髮」），性別不符時整格隱藏。
// en 內可用 {poss} 代名詞佔位符：組句時依性別自動填入 her/his，未選性別時填 their。

const PROMPT_DATA = [
  /* ========== 畫面設定 ========== */
  {
    category: "畫風",
    group: "畫面設定",
    icon: "🎨",
    hue: 265,
    words: [
      { zh: "厚塗", en: "impasto painting style", slug: "impasto" },
      { zh: "水彩", en: "watercolor style", slug: "watercolor" },
      { zh: "動漫風格", en: "anime style", slug: "anime-style" },
      { zh: "扁平插畫", en: "flat illustration", slug: "flat-illust" },
      { zh: "半寫實", en: "semi-realistic style", slug: "semi-realistic" },
      { zh: "半寫實寫真插畫", en: "semi-realistic portrait illustration", slug: "semi-realistic-portrait" },
      { zh: "奇幻油畫", en: "exquisite fantasy oil painting", slug: "fantasy-oil-painting" },
      { zh: "復古油畫", en: "vintage oil painting style", slug: "vintage-oil-painting" },
      { zh: "Y2K風", en: "Y2K aesthetic", slug: "y2k" },
      { zh: "絕佳傑作", en: "masterpiece", slug: "masterpiece" },
      { zh: "暗黑戀愛漫畫封面", en: "dark romance manhwa premium cover art", slug: "dark-romance-manhwa-cover" },
      { zh: "電影感", en: "cinematic", slug: "cinematic" }
    ]
  },
  {
    category: "構圖視角",
    group: "畫面設定",
    icon: "📷",
    hue: 210,
    words: [
      { zh: "特寫", en: "close-up shot", slug: "close-up" },
      { zh: "全身", en: "full body shot", slug: "full-body" },
      { zh: "仰視", en: "low angle view", slug: "low-angle" },
      { zh: "俯視", en: "high angle view", slug: "high-angle" },
      { zh: "側面", en: "side profile", slug: "side-profile" },
      { zh: "動態構圖", en: "dynamic composition", slug: "dynamic-comp" },
      { zh: "廣角景深", en: "wide angle depth of field", slug: "wide-angle" },
      { zh: "多角度視角", en: "multi-angle view", slug: "multi-angle-view" },
      { zh: "半身", en: "half body shot", slug: "half-body" },
      { zh: "正面", en: "front face", slug: "front-face" },
      { zh: "側身看鏡頭", en: "side profile looking at viewer", slug: "side-look-viewer" },
      { zh: "上半身照", en: "upper body shot", slug: "upper-body" },
      { zh: "中景鏡頭", en: "medium shot", slug: "medium-shot" },
      { zh: "35mm鏡頭", en: "35mm lens", slug: "35mm-lens" },
      { zh: "景深", en: "depth of field", slug: "depth-of-field" },
      { zh: "動態模糊", en: "motion blur", slug: "motion-blur" }
    ]
  },
  {
    category: "色調氛圍",
    group: "畫面設定",
    icon: "🌈",
    hue: 320,
    words: [
      { zh: "粉彩色系", en: "pastel color palette", slug: "pastel" },
      { zh: "高飽和", en: "vibrant saturated colors", slug: "vibrant" },
      { zh: "低飽和霧感", en: "muted desaturated tones", slug: "muted" },
      { zh: "暖色調", en: "warm color tones", slug: "warm-tone" },
      { zh: "冷色調", en: "cool color tones", slug: "cool-tone" },
      { zh: "夢幻朦朧", en: "dreamy hazy atmosphere", slug: "dreamy" },
      { zh: "黑暗奇幻", en: "dark fantasy mood", slug: "dark-fantasy" },
      { zh: "魔幻夢境", en: "magical and dreamy atmosphere", slug: "magical-dreamy" },
      { zh: "柔和色調", en: "soft tones", slug: "soft-tones" },
      { zh: "恬靜溫柔", en: "gentle and tranquil mood", slug: "tranquil-mood" },
      { zh: "靜謐神聖", en: "quiet and sacred feeling", slug: "sacred-feeling" },
      { zh: "朝氣活潑用色", en: "cheerful vibrant colors", slug: "cheerful-colors" },
      { zh: "美式復古餐廳", en: "retro American diner color palette", slug: "diner-palette" },
      { zh: "淡彩", en: "pale color palette", slug: "pale-tones" },
      { zh: "高鮮明度", en: "highly vivid colors", slug: "high-vivid" },
      { zh: "空靈感性", en: "ethereal and emotional atmosphere", slug: "ethereal-emotional" },
      { zh: "藍黃紅虹彩", en: "iridescent blue-yellow-red", slug: "iridescent-blue-yellow-red" }
    ]
  },
  {
    category: "光影",
    group: "畫面設定",
    icon: "💡",
    hue: 45,
    words: [
      { zh: "逆光", en: "backlighting", slug: "backlight" },
      { zh: "黃金時刻", en: "golden hour lighting", slug: "golden-hour" },
      { zh: "霓虹光", en: "neon lighting", slug: "neon-light" },
      { zh: "柔和漫射光", en: "soft diffused light", slug: "soft-light" },
      { zh: "月光", en: "moonlight", slug: "moonlight" },
      { zh: "電影感打光", en: "cinematic lighting", slug: "cinematic-light" },
      { zh: "光斑透葉", en: "dappled sunlight", slug: "dappled-light" },
      { zh: "細膩光線", en: "delicate lighting", slug: "delicate-lighting" },
      { zh: "晴朗日光", en: "bright sunny daylight", slug: "bright-sunny-daylight" },
      { zh: "溫暖光線", en: "warm lighting", slug: "warm-lighting" },
      { zh: "彩繪玻璃光影", en: "colorful light streaming through stained glass and casting patterns on the floor", slug: "stained-glass-light" },
      { zh: "光影", en: "light and shadow", slug: "light-and-shadow" },
      { zh: "昏暗光線", en: "dimly lit", slug: "dimly-lit" },
      { zh: "明暗對比", en: "chiaroscuro", slug: "chiaroscuro" },
      { zh: "體積生物冷光", en: "volumetric bioluminescent light", slug: "volumetric-bioluminescent-light" },
      { zh: "臉部聚光", en: "spotlight illuminating face", slug: "spotlight-on-face" },
      { zh: "綠光魔法", en: "green magical light", slug: "green-magical-light" }
    ]
  },
  {
    category: "場景",
    group: "畫面設定",
    icon: "🏞",
    hue: 145,
    words: [
      { zh: "櫻花街道", en: "cherry blossom street", slug: "sakura-street" },
      { zh: "夜晚都市", en: "night city", slug: "night-city" },
      { zh: "海邊夕陽", en: "seaside sunset", slug: "seaside-sunset" },
      { zh: "森林深處", en: "deep forest", slug: "deep-forest" },
      { zh: "教室", en: "classroom", slug: "classroom" },
      { zh: "雨中街景", en: "rainy street", slug: "rainy-street" },
      { zh: "星空草原", en: "starry sky meadow", slug: "starry-meadow" },
      { zh: "廢墟遺跡", en: "ancient ruins", slug: "ruins" },
      { zh: "豪宅陽台", en: "balcony of a luxurious mansion", slug: "luxury-mansion-balcony" },
      { zh: "綠色花園迷宮", en: "green garden maze", slug: "green-garden-maze" },
      { zh: "游泳池", en: "swimming pool", slug: "swimming-pool" },
      { zh: "莊嚴教堂", en: "an elegant and solemn church", slug: "solemn-church" },
      { zh: "浴室", en: "bathroom", slug: "bathroom" },
      { zh: "中式室內陽光", en: "sunlight streaming into a Chinese-style interior", slug: "sunlit-chinese-interior" },
      { zh: "街道", en: "street", slug: "street" },
      { zh: "森林", en: "forest", slug: "forest" },
      { zh: "工作室", en: "workshop", slug: "workshop" },
      { zh: "溫暖室內", en: "a warm and cozy interior", slug: "warm-cozy-interior" },
      { zh: "窗外下雪", en: "snow falling outside the window", slug: "snow-outside-window" },
      { zh: "玫瑰花園", en: "a rose garden", slug: "rose-garden" },
      { zh: "夜晚", en: "at night", slug: "at-night" },
      { zh: "宅邸室內", en: "mansion interior", slug: "mansion-interior" },
      { zh: "空無背景", en: "void background", slug: "void-background" }
    ]
  },
  /* ========== 角色設定 ========== */
  // 髮型六分類，依 niji 建議寫作順序：長度 → 質地 → 瀏海 → 造型 → 顏色 → 髮飾
  // single: true = 該分類單選（重選自動替換）
  // detail: true = 不顯示分類格子，改在髮型細節區選（髮色）；effect: true = 細節區的「效果」複選詞
  {
    category: "髮型長度",
    group: "角色設定",
    icon: "📏",
    hue: 20,
    single: true,
    words: [
      { zh: "光頭", en: "bald", slug: "bald" },
      { zh: "平頭", en: "buzz cut", slug: "buzz-cut", gender: "m" },
      { zh: "寸頭", en: "butch cut", slug: "butch-cut", gender: "m" },
      { zh: "三分頭", en: "high and tight", slug: "high-and-tight", gender: "m" },
      { zh: "短髮", en: "short hair", slug: "short-hair" },
      { zh: "短碎髮", en: "textured crop", slug: "textured-crop", gender: "m" },
      { zh: "耳上短髮", en: "above-ear hair", slug: "above-ear", gender: "m" },
      { zh: "鮑伯頭", en: "bob cut", slug: "bob-cut", gender: "f" },
      { zh: "下巴長度", en: "chin-length hair", slug: "chin-length", gender: "f" },
      { zh: "中短髮", en: "medium-short hair", slug: "medium-short", gender: "m" },
      { zh: "及頸", en: "neck-length hair", slug: "neck-length", gender: "m" },
      { zh: "及肩", en: "shoulder-length hair", slug: "shoulder-length" },
      { zh: "中長髮", en: "medium-length hair", slug: "medium-length" },
      { zh: "中長鮑伯", en: "long bob", slug: "long-bob", gender: "f" },
      { zh: "長髮", en: "long hair", slug: "long-hair" },
      { zh: "及背長髮", en: "back-length hair", slug: "back-length", gender: "m" },
      { zh: "及腰", en: "waist-length hair", slug: "waist-length", gender: "f" },
      { zh: "及臀", en: "hip-length hair", slug: "hip-length", gender: "f" },
      { zh: "超長髮", en: "absurdly long hair", slug: "absurdly-long-hair" }
    ]
  },
  {
    category: "髮質捲度",
    group: "角色設定",
    icon: "🌀",
    hue: 50,
    single: true,
    words: [
      { zh: "直髮", en: "straight hair", slug: "straight-hair" },
      { zh: "微捲", en: "wavy hair", slug: "wavy-hair" },
      { zh: "大波浪", en: "loose waves", slug: "loose-waves", gender: "f" },
      { zh: "捲髮", en: "curly hair", slug: "curly-hair" },
      { zh: "螺旋捲", en: "ringlets", slug: "ringlets", gender: "f" },
      { zh: "細捲", en: "coily hair", slug: "coily-hair" },
      { zh: "爆炸頭", en: "afro", slug: "afro" },
      { zh: "髮量豐厚", en: "voluminous hair", slug: "voluminous-hair" },
      { zh: "細軟髮", en: "fine hair", slug: "fine-hair", gender: "f" },
      { zh: "髮量稀疏", en: "thinning hair", slug: "thinning-hair", gender: "m" },
      { zh: "絲滑", en: "silky hair", slug: "silky-hair" },
      { zh: "服貼", en: "sleek hair", slug: "sleek-hair", gender: "m" },
      { zh: "抓髮蠟", en: "styled with wax", slug: "wax-styled", gender: "m" },
      { zh: "蓬鬆", en: "fluffy hair", slug: "fluffy-hair" },
      { zh: "飄逸", en: "flowing hair", slug: "flowing-hair", gender: "f" },
      { zh: "髮絲飛揚", en: "floating hair", slug: "floating-hair", gender: "f" },
      { zh: "濕髮", en: "wet hair", slug: "wet-hair" },
      { zh: "分層層次", en: "layered hair", slug: "layered-hair" },
      { zh: "內彎", en: "inward curl", slug: "inward-curl", gender: "f" },
      { zh: "外翹", en: "outward flip", slug: "outward-flip" }
    ]
  },
  {
    category: "瀏海",
    group: "角色設定",
    icon: "✂️",
    hue: 70,
    single: true,
    words: [
      { zh: "無瀏海", en: "no bangs", slug: "no-bangs" },
      { zh: "全往後梳", en: "swept-back hair", slug: "swept-back", gender: "m" },
      { zh: "齊瀏海", en: "blunt bangs", slug: "blunt-bangs" },
      { zh: "碎瀏海", en: "choppy bangs", slug: "choppy-bangs", gender: "m" },
      { zh: "空氣瀏海", en: "wispy bangs", slug: "wispy-bangs" },
      { zh: "眉上瀏海", en: "baby bangs", slug: "baby-bangs", gender: "f" },
      { zh: "側分瀏海", en: "side-swept bangs", slug: "side-swept-bangs" },
      { zh: "斜瀏海", en: "asymmetrical bangs", slug: "asymmetrical-bangs" },
      { zh: "法式瀏海", en: "curtain bangs", slug: "curtain-bangs", gender: "f" },
      { zh: "眉毛長度瀏海", en: "eyebrow-length bangs", slug: "eyebrow-length-bangs" },
      { zh: "遮眼瀏海", en: "hair over eyes", slug: "hair-over-eyes" },
      { zh: "遮單眼", en: "hair covering one eye", slug: "hair-over-one-eye", gender: "m" },
      { zh: "額前碎髮", en: "loose strands over forehead", slug: "loose-strands", gender: "m" },
      { zh: "M字瀏海", en: "hime cut sidelocks", slug: "hime-sidelocks", gender: "f" },
      { zh: "中分", en: "center parted hair", slug: "center-part" },
      { zh: "旁分", en: "side part", slug: "side-part" },
      { zh: "三七分", en: "deep side part", slug: "deep-side-part" },
      { zh: "逗號瀏海", en: "comma bangs", slug: "comma-bangs", gender: "m" },
      { zh: "呆毛", en: "ahoge", slug: "ahoge" }
    ]
  },
  {
    category: "髮型造型",
    group: "角色設定",
    icon: "💇",
    hue: 330,
    single: true,
    words: [
      { zh: "馬尾", en: "ponytail", slug: "ponytail" },
      { zh: "高馬尾", en: "high ponytail", slug: "high-ponytail", gender: "f" },
      { zh: "低馬尾", en: "low ponytail", slug: "low-ponytail" },
      { zh: "側馬尾", en: "side ponytail", slug: "side-ponytail", gender: "f" },
      { zh: "雙馬尾", en: "twintails", slug: "twintails", gender: "f" },
      { zh: "低雙馬尾", en: "low twintails", slug: "low-twintails", gender: "f" },
      { zh: "丸子頭", en: "hair bun", slug: "hair-bun", gender: "f" },
      { zh: "雙丸子頭", en: "double buns", slug: "double-buns", gender: "f" },
      { zh: "包頭", en: "chignon", slug: "chignon", gender: "f" },
      { zh: "髮髻", en: "updo", slug: "updo", gender: "f" },
      { zh: "凌亂丸子頭", en: "messy bun", slug: "messy-bun", gender: "f" },
      { zh: "三股辮", en: "braid", slug: "braid", gender: "f" },
      { zh: "單邊辮", en: "side braid", slug: "side-braid", gender: "f" },
      { zh: "雙辮", en: "twin braids", slug: "twin-braids", gender: "f" },
      { zh: "魚骨辮", en: "fishtail braid", slug: "fishtail-braid", gender: "f" },
      { zh: "法式辮", en: "french braid", slug: "french-braid", gender: "f" },
      { zh: "荷蘭辮", en: "dutch braid", slug: "dutch-braid", gender: "f" },
      { zh: "皇冠辮", en: "crown braid", slug: "crown-braid", gender: "f" },
      { zh: "半綁", en: "half updo", slug: "half-updo" },
      { zh: "半丸子", en: "half-up bun", slug: "half-up-bun", gender: "f" },
      { zh: "公主切", en: "hime cut", slug: "hime-cut", gender: "f" },
      { zh: "狼尾", en: "wolf cut", slug: "wolf-cut" },
      { zh: "水母頭", en: "jellyfish cut", slug: "jellyfish-cut", gender: "f" },
      { zh: "蓬鬆亂髮", en: "messy hair", slug: "messy-hair" },
      { zh: "髮盤起", en: "hair up", slug: "hair-up" },
      { zh: "髮放下", en: "hair down", slug: "hair-down" },
      { zh: "兩側推高", en: "undercut", slug: "undercut", gender: "m" },
      { zh: "漸層推剪", en: "fade", slug: "fade", gender: "m" },
      { zh: "低漸層", en: "low fade", slug: "low-fade", gender: "m" },
      { zh: "中漸層", en: "mid fade", slug: "mid-fade", gender: "m" },
      { zh: "高漸層", en: "high fade", slug: "high-fade", gender: "m" },
      { zh: "削邊", en: "skin fade", slug: "skin-fade", gender: "m" },
      { zh: "油頭", en: "pompadour", slug: "pompadour", gender: "m" },
      { zh: "背頭", en: "slicked-back undercut", slug: "slicked-back-undercut", gender: "m" },
      { zh: "側背頭", en: "side part with fade", slug: "side-part-fade", gender: "m" },
      { zh: "飛機頭", en: "quiff", slug: "quiff", gender: "m" },
      { zh: "莫霍克", en: "mohawk", slug: "mohawk", gender: "m" },
      { zh: "假莫霍克", en: "faux hawk", slug: "faux-hawk", gender: "m" },
      { zh: "刺蝟頭", en: "spiky hair", slug: "spiky-hair", gender: "m" },
      { zh: "蘑菇頭", en: "bowl cut", slug: "bowl-cut", gender: "m" },
      { zh: "蓋頭髮", en: "mop top", slug: "mop-top", gender: "m" },
      { zh: "韓系空氣感", en: "korean perm", slug: "korean-perm", gender: "m" },
      { zh: "男版狼尾", en: "modern mullet", slug: "modern-mullet", gender: "m" },
      { zh: "小辮子", en: "small braid", slug: "small-braid", gender: "m" },
      { zh: "髒辮", en: "dreadlocks", slug: "dreadlocks", gender: "m" },
      { zh: "玉米辮", en: "cornrows", slug: "cornrows", gender: "m" },
      { zh: "綁髻", en: "topknot", slug: "topknot", gender: "m" },
      { zh: "武士頭", en: "samurai topknot", slug: "samurai-topknot", gender: "m" },
      { zh: "鑽頭捲", en: "drill hair", slug: "drill-hair", gender: "f" },
      { zh: "雙鑽頭捲", en: "twin drills", slug: "twin-drills", gender: "f" },
      { zh: "公主捲", en: "princess curls", slug: "princess-curls", gender: "f" },
      { zh: "高雙馬尾", en: "high twintails", slug: "high-twintails", gender: "f" },
      { zh: "短雙馬尾", en: "short twintails", slug: "short-twintails", gender: "f" },
      { zh: "單側綁髮", en: "one side up hairstyle", slug: "one-side-up", gender: "f" },
      { zh: "雙側綁髮", en: "two side up hairstyle", slug: "two-side-up", gender: "f" },
      { zh: "辮子馬尾", en: "braided ponytail", slug: "braided-ponytail" },
      { zh: "辮子丸子頭", en: "braided bun", slug: "braided-bun", gender: "f" },
      { zh: "摺疊馬尾", en: "folded ponytail", slug: "folded-ponytail", gender: "f" },
      { zh: "低綁長髮", en: "low-tied long hair", slug: "low-tied-long-hair" }
    ]
  },
  {
    category: "髮色",
    group: "角色設定",
    icon: "🖌️",
    hue: 260,
    detail: true,
    words: [
      { zh: "黑髮", en: "black hair", slug: "black-hair" },
      { zh: "棕髮", en: "brown hair", slug: "brown-hair" },
      { zh: "深棕", en: "dark brown hair", slug: "dark-brown-hair" },
      { zh: "亞麻", en: "ash brown hair", slug: "ash-brown-hair" },
      { zh: "金髮", en: "blonde hair", slug: "blonde-hair" },
      { zh: "白金", en: "platinum blonde", slug: "platinum-blonde" },
      { zh: "銀髮", en: "silver hair", slug: "silver-hair" },
      { zh: "白髮", en: "white hair", slug: "white-hair" },
      { zh: "紅髮", en: "red hair", slug: "red-hair" },
      { zh: "橘髮", en: "orange hair", slug: "orange-hair" },
      { zh: "粉髮", en: "pink hair", slug: "pink-hair", gender: "f" },
      { zh: "紫髮", en: "purple hair", slug: "purple-hair" },
      { zh: "藍髮", en: "blue hair", slug: "blue-hair" },
      { zh: "深藍髮", en: "dark blue hair", slug: "dark-blue-hair" },
      { zh: "綠髮", en: "green hair", slug: "green-hair" },
      { zh: "亮紅髮", en: "bright red hair", slug: "bright-red-hair" },
      // effect: 染髮效果（單選）。two: 需要第二色；tpl: 組句模板，{a}=基本色、{b}=第二色（顏色名不含 hair）
      { zh: "漸層", en: "gradient hair", slug: "gradient-hair", effect: true, two: true, tpl: "{a} to {b} gradient hair" },
      { zh: "挑染", en: "highlights", slug: "hair-highlights", effect: true, two: true, tpl: "{a} hair with {b} highlights" },
      { zh: "內層染", en: "underlights", slug: "underlights", gender: "f", effect: true, two: true, tpl: "{a} hair with {b} underlights" },
      { zh: "雙色", en: "split-dye hair", slug: "split-dye", effect: true, two: true, tpl: "{a} and {b} split-dye hair" },
      { zh: "髮尾漸淡", en: "ombre hair", slug: "ombre-hair", effect: true, two: true, tpl: "{a} to {b} ombre hair" },
      { zh: "髮梢挑色", en: "colored tips", slug: "colored-tips", gender: "f", effect: true, two: true, tpl: "{a} hair with {b} tips" },
      { zh: "髮根深色", en: "dark roots", slug: "dark-roots", gender: "m", effect: true, tpl: "{a} hair with dark roots" },
      { zh: "灰白夾雜", en: "salt and pepper hair", slug: "salt-and-pepper", gender: "m", effect: true }
    ]
  },
  {
    category: "臉部毛髮",
    group: "角色設定",
    icon: "🧔",
    hue: 15,
    gender: "m", // 男性專屬分類：選 1girl 時整格隱藏
    words: [
      { zh: "乾淨無鬍", en: "clean-shaven", slug: "clean-shaven" },
      { zh: "鬍渣", en: "stubble", slug: "stubble" },
      { zh: "短鬍", en: "short beard", slug: "short-beard" },
      { zh: "落腮鬍", en: "full beard", slug: "full-beard" },
      { zh: "山羊鬍", en: "goatee", slug: "goatee" },
      { zh: "八字鬍", en: "mustache", slug: "mustache" },
      { zh: "鬢角", en: "sideburns", slug: "sideburns" },
      { zh: "長鬢角", en: "long sideburns", slug: "long-sideburns" }
    ]
  },
  {
    category: "髮飾",
    group: "角色設定",
    icon: "🎀",
    hue: 200,
    single: true,
    words: [
      { zh: "髮帶", en: "headband", slug: "headband" },
      { zh: "蕾絲髮帶", en: "lace headband", slug: "lace-headband", gender: "f" },
      { zh: "女僕頭飾", en: "maid headdress", slug: "maid-headdress", gender: "f" },
      { zh: "髮夾", en: "hair clip", slug: "hair-clip" },
      { zh: "蝴蝶結", en: "hair bow", slug: "hair-bow", gender: "f" },
      { zh: "髮圈", en: "scrunchie", slug: "scrunchie", gender: "f" },
      { zh: "髮箍", en: "hair hoop", slug: "hair-hoop" },
      { zh: "髮網", en: "hairnet", slug: "hairnet", gender: "f" },
      { zh: "頭紗", en: "veil", slug: "veil", gender: "f" },
      { zh: "花冠", en: "flower crown", slug: "flower-crown", gender: "f" },
      { zh: "大型花帽", en: "large flower hat", slug: "large-flower-hat", gender: "f" },
      { zh: "髮簪", en: "kanzashi", slug: "kanzashi" },
      { zh: "頭巾", en: "bandana", slug: "bandana", gender: "m" },
      { zh: "日式頭巾", en: "hachimaki", slug: "hachimaki", gender: "m" },
      { zh: "耳際夾髮", en: "hair pinned behind ear", slug: "pinned-behind-ear", gender: "m" },
      { zh: "迷你帽", en: "mini hat", slug: "mini-hat", gender: "f" },
      { zh: "頭飾", en: "hair ornament", slug: "hair-ornament" }
    ]
  },
  {
    category: "眼睛",
    group: "角色設定",
    icon: "👁",
    hue: 235,
    words: [
      { zh: "藍色眼睛", en: "blue eyes", slug: "blue-eyes", eyeColor: "blue" },
      { zh: "深藍眼睛", en: "deep blue eyes", slug: "deep-blue-eyes", eyeColor: "deep blue" },
      { zh: "黑色眼睛", en: "black eyes", slug: "black-eyes", eyeColor: "black" },
      { zh: "白色眼睛", en: "white eyes", slug: "white-eyes", eyeColor: "white" },
      { zh: "黑眼圈", en: "dark circles under his eyes", slug: "dark-circles", gender: "m" },
      { zh: "紅色眼睛", en: "red eyes", slug: "red-eyes", eyeColor: "red" },
      { zh: "深紅眼睛", en: "crimson red eyes", slug: "crimson-red-eyes", eyeColor: "crimson red" },
      { zh: "金色眼睛", en: "golden eyes", slug: "golden-eyes", eyeColor: "gold" },
      { zh: "綠色眼睛", en: "green eyes", slug: "green-eyes", eyeColor: "green" },
      { zh: "紫色眼睛", en: "purple eyes", slug: "purple-eyes", eyeColor: "purple" },
      { zh: "異色瞳", en: "heterochromia eyes", slug: "heterochromia", heterochromia: true },
      { zh: "星光眼", en: "sparkling eyes", slug: "sparkling-eyes" },
      { zh: "藍色星空眼", en: "blue starry eyes", slug: "blue-starry-eyes" },
      { zh: "深藍星空眼", en: "starry dark blue eyes", slug: "dark-blue-starry-eyes" },
      { zh: "右眼淚痣", en: "a tear mole under the right eye", slug: "right-eye-tear-mole" },
      { zh: "深棕眼睛", en: "dark brown eyes", slug: "dark-brown-eyes", eyeColor: "dark brown" }
    ]
  },
  {
    category: "氣質特質",
    group: "角色設定",
    icon: "✨",
    hue: 300,
    words: [
      { zh: "成熟優雅", en: "mature and graceful aura", slug: "mature-graceful" },
      { zh: "淑女優雅", en: "ladylike elegance", slug: "ladylike-elegance", gender: "f" },
      { zh: "高貴嚴肅", en: "noble and serious demeanor", slug: "noble-serious", gender: "f" },
      { zh: "成熟男性", en: "mature man", slug: "mature-man", gender: "m" },
      { zh: "五官勻稱", en: "evenly balanced facial features", slug: "balanced-features" },
      { zh: "細緻曲線", en: "delicate curves", slug: "delicate-curves" },
      { zh: "纖細身材", en: "slender figure", slug: "slender-figure" },
      { zh: "元氣桃色妝", en: "fresh peachy makeup", slug: "peachy-makeup", gender: "f" },
      { zh: "皮膚蒼白", en: "pale skin", slug: "pale-skin" },
      { zh: "沾到鮮奶油", en: "dabs of whipped cream on the nose and shoulders", slug: "cream-dabs" },
      { zh: "英俊", en: "handsome", slug: "handsome" },
      { zh: "威嚇逼近感", en: "intimidating and looming", slug: "intimidating-looming" }
    ]
  },
  {
    category: "表情",
    group: "角色設定",
    icon: "😊",
    hue: 0,
    words: [
      { zh: "溫柔微笑", en: "gentle smile", slug: "gentle-smile" },
      { zh: "開朗大笑", en: "cheerful laugh", slug: "cheerful-laugh" },
      { zh: "害羞臉紅", en: "shy blushing", slug: "shy-blush" },
      { zh: "冷酷眼神", en: "cold stare", slug: "cold-stare" },
      { zh: "驚訝", en: "surprised expression", slug: "surprised" },
      { zh: "含淚", en: "teary eyes", slug: "teary-eyes" },
      { zh: "俏皮眨眼", en: "playful wink", slug: "playful-wink" },
      { zh: "睡意惺忪", en: "sleepy expression on {poss} face", slug: "sleepy-expression" },
      { zh: "溫柔凝視", en: "soft and gentle gaze", slug: "gentle-gaze" },
      { zh: "甜蜜喜悅笑容", en: "sweet and joyful smile", slug: "sweet-joyful-smile" },
      { zh: "驚恐", en: "a frightened expression", slug: "frightened-expression" },
      { zh: "冷顏", en: "a cold expression", slug: "cold-expression" },
      { zh: "淡然不為所動", en: "unbothered", slug: "unbothered" }
    ]
  },
  {
    category: "服裝",
    group: "角色設定",
    icon: "👗",
    hue: 180,
    words: [
      { zh: "水手服", en: "sailor school uniform", slug: "sailor-uniform" },
      { zh: "哥德蘿莉", en: "gothic lolita dress", slug: "gothic-lolita" },
      { zh: "和服", en: "traditional kimono", slug: "kimono" },
      { zh: "旗袍", en: "cheongsam dress", slug: "cheongsam" },
      { zh: "騎士鎧甲", en: "knight armor", slug: "knight-armor" },
      { zh: "魔法師長袍", en: "wizard robe", slug: "wizard-robe" },
      { zh: "休閒連帽衫", en: "casual hoodie", slug: "hoodie" },
      { zh: "黑框眼鏡", en: "black-framed glasses", slug: "black-framed-glasses" },
      { zh: "白色實驗袍", en: "white lab coat", slug: "white-lab-coat" },
      { zh: "深藍金邊襯衫", en: "deep blue shirt with gold trim", slug: "blue-gold-shirt", gender: "m" },
      { zh: "黑色西裝褲", en: "black suit pants", slug: "black-suit-pants", gender: "m" },
      { zh: "白色祭司袍", en: "white priestly robes", slug: "white-priestly-robes", gender: "f" },
      { zh: "白色新郎禮服", en: "white groom's outfit", slug: "white-groom-outfit", gender: "m" },
      { zh: "米色校服", en: "beige school uniform", slug: "beige-school-uniform" },
      { zh: "禮服", en: "elegant evening gown", slug: "evening-gown" },
      { zh: "公主服", en: "princess dress", slug: "princess-dress" },
      { zh: "蕾絲白睡衣", en: "puffy pure white pajama with sleeves and edges decorated with lace", slug: "white-lace-pajama" },
      { zh: "方框眼鏡", en: "square-framed glasses", slug: "square-framed-glasses" },
      { zh: "白色短袖", en: "white short-sleeved shirt", slug: "white-short-sleeved-shirt" },
      { zh: "卡其色短褲", en: "khaki shorts", slug: "khaki-shorts" },
      { zh: "墨鏡", en: "sunglasses", slug: "sunglasses" },
      { zh: "印花短袖襯衫", en: "printed short-sleeved shirt", slug: "printed-short-sleeved-shirt" },
      { zh: "寬鬆長褲", en: "loose-fitting pants", slug: "loose-fitting-pants" },
      { zh: "白色古風服裝", en: "white traditional Chinese attire", slug: "white-chinese-attire" },
      { zh: "護目鏡", en: "protective goggles", slug: "protective-goggles" },
      { zh: "橘色短袖", en: "orange short-sleeved shirt", slug: "orange-short-sleeved-shirt" },
      { zh: "棉褲", en: "cotton pants", slug: "cotton-pants" },
      { zh: "拖鞋", en: "slippers", slug: "slippers" },
      { zh: "黑色襯衫", en: "black shirt", slug: "black-shirt" },
      { zh: "白色西裝褲", en: "white suit pants", slug: "white-suit-pants" },
      { zh: "紅色領帶", en: "red tie", slug: "red-tie" },
      { zh: "粉色毛衣", en: "pink sweater", slug: "pink-sweater" },
      { zh: "粉紅色小禮服", en: "pink mini dress", slug: "pink-mini-dress", gender: "f" },
      { zh: "襯衫", en: "shirt", slug: "clothing-shirt", colorable: true },
      { zh: "短袖上衣", en: "short-sleeved shirt", slug: "clothing-short-sleeved-shirt", colorable: true },
      { zh: "連身裙", en: "dress", slug: "clothing-dress", colorable: true, gender: "f" },
      { zh: "小禮服", en: "mini dress", slug: "clothing-mini-dress", colorable: true, gender: "f" },
      { zh: "毛衣", en: "sweater", slug: "clothing-sweater", colorable: true },
      { zh: "長褲", en: "pants", slug: "clothing-pants", colorable: true },
      { zh: "短褲", en: "shorts", slug: "clothing-shorts", colorable: true },
      { zh: "西裝褲", en: "suit pants", slug: "clothing-suit-pants", colorable: true },
      { zh: "領帶", en: "tie", slug: "clothing-tie", colorable: true },
      { zh: "古風服裝", en: "traditional Chinese attire", slug: "clothing-chinese-attire", colorable: true },
      { zh: "黑色兜帽", en: "black hood", slug: "black-hood" },
      { zh: "白色扣領襯衫", en: "white button-up shirt", slug: "white-button-up-shirt" }
    ]
  },
  {
    category: "動作姿勢",
    group: "角色設定",
    icon: "🕺",
    hue: 95,
    words: [
      { zh: "回眸", en: "looking back over shoulder", slug: "looking-back" },
      { zh: "奔跑", en: "running pose", slug: "running" },
      { zh: "坐姿", en: "sitting pose", slug: "sitting" },
      { zh: "躺臥", en: "lying down", slug: "lying-down" },
      { zh: "伸手向前", en: "reaching out hand", slug: "reaching-out" },
      { zh: "跳躍", en: "jumping mid-air", slug: "jumping" },
      { zh: "陽台佇立", en: "standing on the balcony", slug: "standing-on-balcony" },
      { zh: "坐在窗台", en: "sitting by the window", slug: "sitting-window" },
      { zh: "柔軟動作", en: "soft graceful pose", slug: "soft-pose" },
      { zh: "單手撐在窗邊", en: "one hand braced against the window frame", slug: "one-hand-on-window" },
      { zh: "一手擋太陽", en: "shielding the sunlight with one hand", slug: "shielding-sunlight" },
      { zh: "單手撐頭", en: "resting {poss} head on one hand", slug: "head-on-one-hand" },
      { zh: "維修物品", en: "repairing something", slug: "repairing-something" },
      { zh: "看向窗戶", en: "looking toward the window", slug: "looking-toward-window" },
      { zh: "坐在沙發上", en: "sitting on a sofa", slug: "sitting-on-sofa" },
      { zh: "身蓋毯子", en: "covered with a blanket", slug: "covered-with-blanket" },
      { zh: "花園下午茶", en: "sitting and enjoying afternoon tea in the rose garden", slug: "rose-garden-afternoon-tea" },
      { zh: "S曲線", en: "S-curve pose", slug: "s-curve-pose", gender: "f" },
      { zh: "張腿而坐", en: "manspreading", slug: "manspreading", gender: "m" },
      { zh: "施放咒語", en: "casting a spell", slug: "casting-a-spell" }
    ]
  },
  {
    category: "隨身道具",
    group: "角色設定",
    icon: "🔮",
    hue: 120,
    single: true,
    picker: "item",
    words: [
      { zh: "魔法古書", en: "the book cover made of brown leather with four golden corners is opened and resting in {poss} hands", slug: "magic-book" },
      { zh: "木製魔杖", en: "holding a wooden magic wand", slug: "wooden-magic-wand" },
      { zh: "手持香菸盒", en: "holding a pack of cigarettes", slug: "cigarette-pack", gender: "m" },
      { zh: "手持書卷", en: "holding a scroll", slug: "holding-scroll" },
      { zh: "手持木劍", en: "holding a wooden sword", slug: "holding-wooden-sword" },
      { zh: "手持毛筆", en: "holding a calligraphy brush", slug: "holding-calligraphy-brush" },
      { zh: "手持螺絲起子", en: "holding a screwdriver", slug: "holding-screwdriver" },
      { zh: "手持手機", en: "holding a smartphone", slug: "holding-smartphone" },
      { zh: "手持聖經", en: "holding a Bible", slug: "holding-bible" },
      { zh: "手持書本", en: "holding a book", slug: "holding-book-generic" },
      { zh: "手持玫瑰花", en: "holding a rose", slug: "holding-rose" }
    ]
  },
  /* ========== 背景裝飾（輸出時排在最後） ========== */
  {
    category: "裝飾元素",
    group: "背景裝飾",
    icon: "🏛",
    hue: 30,
    words: [
      { zh: "金色巴洛克邊框", en: "golden Baroque ornament border", slug: "baroque-border" },
      { zh: "實驗與魔法設備", en: "various laboratory instruments and magical equipment in the background", slug: "lab-magic-equipment" },
      { zh: "黑霧環繞", en: "surrounded by black mist", slug: "surrounded-black-mist" },
      { zh: "紅花環繞", en: "surrounded by red flowers", slug: "surrounded-red-flowers" },
      { zh: "橘貓相伴", en: "an orange cat nearby", slug: "orange-cat-nearby" },
      { zh: "鬼怪", en: "a ghostly apparition", slug: "ghostly-apparition" },
      { zh: "石桌", en: "a stone table", slug: "stone-table" },
      { zh: "壁爐", en: "a fireplace", slug: "fireplace" },
      { zh: "爐火", en: "a warm fire burning in the fireplace", slug: "fireplace-fire" },
      { zh: "日月飾球", en: "a sun and a moon decorative orb surrounding by {poss} side, orbs emitting a soft orange glow", slug: "sun-moon-orbs" },
      { zh: "桌上黃金聖杯", en: "a golden chalice displayed on the table in front", slug: "golden-chalice-table" },
      { zh: "桌上長劍", en: "a sword displayed on the table in front", slug: "sword-on-table" },
      { zh: "大袋金幣", en: "a large bag of gold coins placed on the tabletop", slug: "large-bag-gold-coins" },
      { zh: "皮革椅", en: "a leather chair", slug: "leather-chair" }
    ]
  },
  {
    category: "神聖的裝飾",
    group: "背景裝飾",
    icon: "✨",
    hue: 265,
    words: [
      { zh: "星空石雕", en: "mystique of starry stone carvings", slug: "starry-stone-carving" },
      { zh: "天空石雕背景", en: "a sky stone-carved background", slug: "sky-stone-background" },
      { zh: "聖光光環", en: "a halo of sacred light behind her head", slug: "sacred-light-halo", gender: "f" },
      { zh: "黑白立柱", en: "black and white pillars on their left and right respectively", slug: "black-white-pillars" },
      { zh: "新月圖騰", en: "a decorative crescent moon totem centered at their feet", slug: "crescent-moon-totem" }
    ]
  },
  {
    category: "飄落物",
    group: "背景裝飾",
    icon: "🍃",
    hue: 340,
    words: [
      { zh: "粉色花瓣飄舞", en: "surrounded by fluttering pink petals", slug: "fluttering-pink-petals" },
      { zh: "彩色泡泡漂浮", en: "colorful bubbles floating around", slug: "floating-colorful-bubbles" }
    ]
  },
  {
    category: "主題甜點",
    group: "背景裝飾",
    icon: "🍨",
    hue: 55,
    words: [
      { zh: "霧面球狀冰淇淋", en: "plump matte ice cream scoops with soft texture", slug: "matte-ice-cream" },
      { zh: "蜂蜜銀珠黃冰淇淋", en: "yellow ice cream topped with silver pearls and honey drizzle", slug: "yellow-honey-ice-cream" },
      { zh: "黑白夾心餅乾", en: "black sandwich cookies with white cream filling", slug: "sandwich-cookies" }
    ]
  }
];
