$ErrorActionPreference = "Stop"

$projectRoot = $PSScriptRoot
$imageRoot = Join-Path $projectRoot "images"
$outputFile = Join-Path $projectRoot "js\image-index.js"
$supportedExtensions = @(".jpg", ".jpeg", ".png", ".webp", ".gif", ".avif")

$files = Get-ChildItem -LiteralPath $imageRoot -Recurse -File |
  Where-Object { $supportedExtensions -contains $_.Extension.ToLowerInvariant() } |
  Sort-Object FullName |
  ForEach-Object {
    $relativePath = $_.FullName.Substring($projectRoot.Length + 1).Replace("\", "/")
    "  " + ($relativePath | ConvertTo-Json -Compress)
  }

$content = @(
  "/* Generated by update-image-index.ps1. Do not edit manually. */"
  "window.IMAGE_FILES = ["
  ($files -join ",`r`n")
  "];"
) -join "`r`n"

[System.IO.File]::WriteAllText($outputFile, $content, [System.Text.UTF8Encoding]::new($false))
Write-Host "Image index updated: $($files.Count) file(s)"
